<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../registerUser.wsdl"/>
      <rootElement name="User" namespace="http://www.ihorizons.com/soa"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="../crudUser.wsdl"/>
      <rootElement name="UsersCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/crudUser"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.7.8(build 150622.2350.0222) AT [THU AUG 20 13:56:33 EET 2015]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/crudUser"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:inp1="http://www.ihorizons.com/soa"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:ns0="http://xmlns.oracle.com/pcbpel/adapter/db/Lab1/Registration/crudUser"
                xmlns:tns="http://oracle.com/sca/soapservice/Lab1/Registration/registerUser"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:bpmn="http://schemas.oracle.com/bpm/xpath"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl wsdl inp1 tns xsd top plt ns0 xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref bpmn ldap">
  <xsl:template match="/">
    <top:UsersCollection>
      <top:Users>
        <top:userName>
          <xsl:value-of select="/inp1:User/inp1:userName"/>
        </top:userName>
        <top:firstName>
          <xsl:value-of select="/inp1:User/inp1:firstName"/>
        </top:firstName>
        <top:lastName>
          <xsl:value-of select="/inp1:User/inp1:lastName"/>
        </top:lastName>
        <top:gender>
          <xsl:value-of select="/inp1:User/inp1:gender"/>
        </top:gender>
        <top:password>
          <xsl:value-of select="/inp1:User/inp1:password"/>
        </top:password>
      </top:Users>
    </top:UsersCollection>
  </xsl:template>
</xsl:stylesheet>
